[versions]
detekt = "1.23.1"
kotlinx-coroutines = "1.7.2"
kotlin = "1.9.0"
android = "8.0.2"
git-hooks = "0.0.2"
nexus = "1.1.0"
atomicfu = "0.21.0"
dokka = "1.7.20"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-recyclerview = "1.3.1"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-git-hooks = { module = "com.github.jakemarsden:git-hooks-gradle-plugin", version.ref = "git-hooks" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-nexus = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus" }
plugin-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicfu" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }